// ============================================================
// CrustIntel — Realistic Mock Data for Competitive Intelligence
// Built on Crustdata API data shapes
// ============================================================

export const TRACKED_COMPANY = {
  id: 'self_001',
  name: 'Crustdata',
  domain: 'crustdata.com',
  logo_emoji: '🦀',
  industry: 'B2B Data Infrastructure',
  description: 'Real-time data layer for AI agents. API-first B2B intelligence covering 60M+ companies and 1B+ people profiles.',
  hq_location: 'San Francisco, CA',
  founded_year: 2023,
  headcount: 18,
  headcount_6m_ago: 9,
  headcount_growth_6m: 100.0,
  funding_total_usd: 6000000,
  funding_stage: 'Seed',
  latest_round_date: '2025-10-15',
  revenue_estimate_usd: 9200000,
  web_traffic_monthly: 185000,
  web_traffic_trend: 'up',
  tech_stack: ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Kafka', 'React'],
  linkedin_url: 'https://linkedin.com/company/crustdata',
  glassdoor_rating: 4.6,
  g2_rating: 4.8,
  threat_level: 'self',
  category: 'self'
};

export const COMPETITORS = [
  {
    id: 'comp_001',
    name: 'Apollo.io',
    domain: 'apollo.io',
    logo_emoji: '🚀',
    industry: 'Sales Intelligence',
    description: 'All-in-one sales intelligence and engagement platform with 275M+ contacts database.',
    hq_location: 'San Francisco, CA',
    founded_year: 2015,
    headcount: 1200,
    headcount_6m_ago: 980,
    headcount_growth_6m: 22.4,
    funding_total_usd: 251000000,
    funding_stage: 'Series D',
    latest_round_date: '2023-08-15',
    revenue_estimate_usd: 200000000,
    web_traffic_monthly: 4500000,
    web_traffic_trend: 'up',
    tech_stack: ['React', 'Ruby on Rails', 'PostgreSQL', 'Elasticsearch', 'AWS'],
    linkedin_url: 'https://linkedin.com/company/apollo-io',
    glassdoor_rating: 3.8,
    g2_rating: 4.7,
    threat_level: 'high',
    category: 'competitor'
  },
  {
    id: 'comp_002',
    name: 'ZoomInfo',
    domain: 'zoominfo.com',
    logo_emoji: '🔍',
    industry: 'B2B Data & Intelligence',
    description: 'Enterprise-grade go-to-market intelligence platform. Publicly traded (NASDAQ: ZI).',
    hq_location: 'Vancouver, WA',
    founded_year: 2000,
    headcount: 3500,
    headcount_6m_ago: 4100,
    headcount_growth_6m: -14.6,
    funding_total_usd: 500000000,
    funding_stage: 'Public (ZI)',
    latest_round_date: '2020-06-04',
    revenue_estimate_usd: 1200000000,
    web_traffic_monthly: 8200000,
    web_traffic_trend: 'down',
    tech_stack: ['Java', 'React', 'Snowflake', 'Kubernetes', 'GCP'],
    linkedin_url: 'https://linkedin.com/company/zoominfo',
    glassdoor_rating: 3.5,
    g2_rating: 4.4,
    threat_level: 'high',
    category: 'competitor'
  },
  {
    id: 'comp_003',
    name: 'Clearbit',
    domain: 'clearbit.com',
    logo_emoji: '💎',
    industry: 'Data Enrichment',
    description: 'B2B data enrichment API, acquired by HubSpot in 2023. Powers real-time data activation.',
    hq_location: 'San Francisco, CA',
    founded_year: 2014,
    headcount: 280,
    headcount_6m_ago: 310,
    headcount_growth_6m: -9.7,
    funding_total_usd: 75000000,
    funding_stage: 'Acquired (HubSpot)',
    latest_round_date: '2023-11-01',
    revenue_estimate_usd: 55000000,
    web_traffic_monthly: 1200000,
    web_traffic_trend: 'stable',
    tech_stack: ['Go', 'React', 'PostgreSQL', 'Redis', 'AWS'],
    linkedin_url: 'https://linkedin.com/company/clearbit',
    glassdoor_rating: 4.0,
    g2_rating: 4.4,
    threat_level: 'medium',
    category: 'competitor'
  },
  {
    id: 'comp_004',
    name: 'People Data Labs',
    domain: 'peopledatalabs.com',
    logo_emoji: '👥',
    industry: 'People Data API',
    description: 'Developer-first people data platform. B2B data as a service with 1.5B+ person records.',
    hq_location: 'San Francisco, CA',
    founded_year: 2015,
    headcount: 120,
    headcount_6m_ago: 95,
    headcount_growth_6m: 26.3,
    funding_total_usd: 38000000,
    funding_stage: 'Series B',
    latest_round_date: '2022-04-20',
    revenue_estimate_usd: 25000000,
    web_traffic_monthly: 320000,
    web_traffic_trend: 'up',
    tech_stack: ['Python', 'Go', 'PostgreSQL', 'Elasticsearch', 'AWS'],
    linkedin_url: 'https://linkedin.com/company/peopledatalabs',
    glassdoor_rating: 4.2,
    g2_rating: 4.5,
    threat_level: 'high',
    category: 'competitor'
  },
  {
    id: 'comp_005',
    name: 'Coresignal',
    domain: 'coresignal.com',
    logo_emoji: '📊',
    industry: 'Alternative Data',
    description: 'Alternative B2B data provider with web-sourced employee, company, and job posting data.',
    hq_location: 'Vilnius, Lithuania',
    founded_year: 2016,
    headcount: 85,
    headcount_6m_ago: 70,
    headcount_growth_6m: 21.4,
    funding_total_usd: 8000000,
    funding_stage: 'Series A',
    latest_round_date: '2022-09-12',
    revenue_estimate_usd: 12000000,
    web_traffic_monthly: 95000,
    web_traffic_trend: 'up',
    tech_stack: ['Python', 'Scala', 'Spark', 'PostgreSQL', 'AWS'],
    linkedin_url: 'https://linkedin.com/company/coresignal',
    glassdoor_rating: 4.1,
    g2_rating: 4.3,
    threat_level: 'medium',
    category: 'competitor'
  },
  {
    id: 'comp_006',
    name: 'Clay',
    domain: 'clay.com',
    logo_emoji: '🧱',
    industry: 'Data Orchestration',
    description: 'Creative data workflow tool for go-to-market teams. Integrates 75+ enrichment providers.',
    hq_location: 'New York, NY',
    founded_year: 2020,
    headcount: 200,
    headcount_6m_ago: 130,
    headcount_growth_6m: 53.8,
    funding_total_usd: 62000000,
    funding_stage: 'Series B',
    latest_round_date: '2024-03-14',
    revenue_estimate_usd: 40000000,
    web_traffic_monthly: 890000,
    web_traffic_trend: 'up',
    tech_stack: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'Vercel'],
    linkedin_url: 'https://linkedin.com/company/clay-hq',
    glassdoor_rating: 4.4,
    g2_rating: 4.6,
    threat_level: 'low',
    category: 'adjacent'
  },
  {
    id: 'comp_007',
    name: 'Cognism',
    domain: 'cognism.com',
    logo_emoji: '🧠',
    industry: 'Sales Intelligence',
    description: 'International sales intelligence platform with phone-verified mobile numbers. Strong in EMEA.',
    hq_location: 'London, UK',
    founded_year: 2015,
    headcount: 600,
    headcount_6m_ago: 550,
    headcount_growth_6m: 9.1,
    funding_total_usd: 87000000,
    funding_stage: 'Series C',
    latest_round_date: '2023-05-10',
    revenue_estimate_usd: 80000000,
    web_traffic_monthly: 1100000,
    web_traffic_trend: 'stable',
    tech_stack: ['Python', 'React', 'AWS', 'Kubernetes', 'Snowflake'],
    linkedin_url: 'https://linkedin.com/company/cognism',
    glassdoor_rating: 4.1,
    g2_rating: 4.6,
    threat_level: 'medium',
    category: 'competitor'
  },
  {
    id: 'comp_008',
    name: 'Lusha',
    domain: 'lusha.com',
    logo_emoji: '📇',
    industry: 'Contact Data',
    description: 'B2B contact data platform with browser extension and CRM integrations. 100M+ business profiles.',
    hq_location: 'Tel Aviv, Israel',
    founded_year: 2016,
    headcount: 350,
    headcount_6m_ago: 380,
    headcount_growth_6m: -7.9,
    funding_total_usd: 205000000,
    funding_stage: 'Series B',
    latest_round_date: '2021-12-02',
    revenue_estimate_usd: 70000000,
    web_traffic_monthly: 1800000,
    web_traffic_trend: 'down',
    tech_stack: ['Node.js', 'React', 'MongoDB', 'Redis', 'AWS'],
    linkedin_url: 'https://linkedin.com/company/lusha',
    glassdoor_rating: 3.7,
    g2_rating: 4.3,
    threat_level: 'medium',
    category: 'competitor'
  },
  {
    id: 'comp_009',
    name: '6sense',
    domain: '6sense.com',
    logo_emoji: '🎯',
    industry: 'ABM & Intent Data',
    description: 'Account-based marketing platform powered by AI and intent data. Enterprise-focused.',
    hq_location: 'San Francisco, CA',
    founded_year: 2013,
    headcount: 1100,
    headcount_6m_ago: 1250,
    headcount_growth_6m: -12.0,
    funding_total_usd: 426000000,
    funding_stage: 'Series E',
    latest_round_date: '2022-06-15',
    revenue_estimate_usd: 180000000,
    web_traffic_monthly: 520000,
    web_traffic_trend: 'stable',
    tech_stack: ['Python', 'Java', 'React', 'Snowflake', 'GCP'],
    linkedin_url: 'https://linkedin.com/company/6sense',
    glassdoor_rating: 3.9,
    g2_rating: 4.3,
    threat_level: 'low',
    category: 'adjacent'
  },
  {
    id: 'comp_010',
    name: 'Seamless.AI',
    domain: 'seamless.ai',
    logo_emoji: '⚡',
    industry: 'AI Lead Generation',
    description: 'Real-time search engine for B2B sales leads powered by AI. 1.9B+ contact records.',
    hq_location: 'Columbus, OH',
    founded_year: 2015,
    headcount: 500,
    headcount_6m_ago: 450,
    headcount_growth_6m: 11.1,
    funding_total_usd: 75000000,
    funding_stage: 'Series A',
    latest_round_date: '2022-08-20',
    revenue_estimate_usd: 90000000,
    web_traffic_monthly: 2100000,
    web_traffic_trend: 'up',
    tech_stack: ['Python', 'React', 'TensorFlow', 'PostgreSQL', 'AWS'],
    linkedin_url: 'https://linkedin.com/company/seamlessai',
    glassdoor_rating: 3.4,
    g2_rating: 4.2,
    threat_level: 'medium',
    category: 'competitor'
  }
];

export const SIGNALS = [
  {
    id: 'sig_001',
    type: 'hiring_surge',
    severity: 'critical',
    icon: '🚨',
    title: 'Apollo.io Posts 15 AI/ML Roles in 2 Weeks',
    description: 'Apollo.io has posted 15 new AI and machine learning engineering roles including "Head of AI Agents" and "Senior ML Engineer — Real-time Data." This is a 300% increase in AI-related job postings compared to the previous quarter.',
    company_id: 'comp_001',
    company_name: 'Apollo.io',
    timestamp: '2026-06-03T09:00:00Z',
    source: 'LinkedIn Jobs',
    source_url: 'https://linkedin.com/company/apollo-io/jobs',
    ai_analysis: 'Apollo\'s aggressive AI hiring signals a strategic push into AI-native data infrastructure — directly competing with Crustdata\'s core positioning. The "Head of AI Agents" role suggests they\'re building an agent-first product layer, potentially undermining Crustdata\'s "data layer for AI agents" thesis. This is the highest-priority competitive signal this quarter.'
  },
  {
    id: 'sig_002',
    type: 'funding',
    severity: 'high',
    icon: '💰',
    title: 'People Data Labs Closes $28M Series C',
    description: 'People Data Labs has raised a $28M Series C led by Craft Ventures, bringing total funding to $66M. The company announced plans to launch real-time data crawling capabilities and an MCP server integration.',
    company_id: 'comp_004',
    company_name: 'People Data Labs',
    timestamp: '2026-06-01T14:30:00Z',
    source: 'TechCrunch',
    source_url: 'https://techcrunch.com/2026/06/01/people-data-labs-series-c',
    ai_analysis: 'PDL\'s move into real-time data crawling and MCP server support represents a direct assault on Crustdata\'s two key differentiators. With $66M total funding vs Crustdata\'s $6M, they have significant resources to execute. The 6-month window before their real-time capabilities mature is critical for Crustdata to cement market position.'
  },
  {
    id: 'sig_003',
    type: 'exec_move',
    severity: 'high',
    icon: '👔',
    title: 'ZoomInfo CTO Departs After 8 Years',
    description: 'ZoomInfo\'s CTO, who led the company\'s data infrastructure since pre-IPO, has departed the company. No replacement has been announced. This follows a 15% headcount reduction over the past 6 months.',
    company_id: 'comp_002',
    company_name: 'ZoomInfo',
    timestamp: '2026-05-30T11:00:00Z',
    source: 'The Information',
    source_url: 'https://theinformation.com/articles/zoominfo-cto-departs',
    ai_analysis: 'ZoomInfo\'s CTO departure combined with significant headcount cuts signals internal instability. This creates a talent acquisition opportunity — displaced ZoomInfo engineers with enterprise data pipeline experience would be highly valuable hires for Crustdata. Recommend monitoring LinkedIn for ZoomInfo departures in the data engineering and ML teams.'
  },
  {
    id: 'sig_004',
    type: 'product_launch',
    severity: 'high',
    icon: '📦',
    title: 'Clay Launches "Clay AI Agent Builder"',
    description: 'Clay has launched an AI Agent Builder that allows users to create autonomous sales workflows using natural language. The builder integrates with 75+ data providers including Crustdata, Apollo, and ZoomInfo.',
    company_id: 'comp_006',
    company_name: 'Clay',
    timestamp: '2026-05-28T16:00:00Z',
    source: 'Product Hunt',
    source_url: 'https://producthunt.com/posts/clay-ai-agent-builder',
    ai_analysis: 'Clay\'s AI Agent Builder is a distribution opportunity, not a threat. As a workflow layer that integrates multiple data providers, Clay amplifies Crustdata\'s reach. However, Clay\'s growing platform power means they could eventually commoditize the data layer. Recommend deepening the Clay integration while building direct customer relationships.'
  },
  {
    id: 'sig_005',
    type: 'talent_flow',
    severity: 'medium',
    icon: '🔄',
    title: '3 Ex-Crustdata Engineers Now at Apollo.io',
    description: 'Three engineers who previously worked at Crustdata have joined Apollo.io\'s data infrastructure team in the past 90 days, including a senior data pipeline engineer and an ML engineer who worked on entity resolution.',
    company_id: 'comp_001',
    company_name: 'Apollo.io',
    timestamp: '2026-05-27T08:00:00Z',
    source: 'LinkedIn',
    source_url: 'https://linkedin.com',
    ai_analysis: 'Talent outflow to a direct competitor is concerning. These engineers carry institutional knowledge about Crustdata\'s data architecture, crawling infrastructure, and entity resolution models. This accelerates Apollo\'s ability to replicate Crustdata\'s technical advantages. Immediate retention review of remaining engineering team is recommended.'
  },
  {
    id: 'sig_006',
    type: 'press',
    severity: 'medium',
    icon: '📰',
    title: 'Cognism Acquires European Data Provider DataSift',
    description: 'Cognism has acquired DataSift, a European alternative data aggregator, for an undisclosed amount. The acquisition adds 15M+ European business profiles and real-time social data capabilities.',
    company_id: 'comp_007',
    company_name: 'Cognism',
    timestamp: '2026-05-25T10:00:00Z',
    source: 'Bloomberg',
    source_url: 'https://bloomberg.com/news/cognism-datasift',
    ai_analysis: 'Cognism\'s acquisition strengthens their European data moat and adds real-time social data capabilities. While Crustdata is primarily US-focused, international expansion will eventually put them in direct competition with a better-resourced Cognism in EMEA markets. Low immediate risk, but worth monitoring.'
  },
  {
    id: 'sig_007',
    type: 'hiring_surge',
    severity: 'medium',
    icon: '👥',
    title: '6sense Posts 12 New ML Engineering Roles',
    description: '6sense has posted 12 machine learning engineering positions focused on "next-generation intent signal detection" and "real-time buyer behavior modeling."',
    company_id: 'comp_009',
    company_name: '6sense',
    timestamp: '2026-05-23T13:00:00Z',
    source: 'LinkedIn Jobs',
    source_url: 'https://linkedin.com/company/6sense/jobs',
    ai_analysis: '6sense\'s ML hiring push for intent signals could create competitive overlap with Crustdata\'s signal detection capabilities. While 6sense focuses on buyer intent (ABM), their "real-time behavior modeling" could expand into the real-time company intelligence space. Adjacent threat worth monitoring.'
  },
  {
    id: 'sig_008',
    type: 'product_launch',
    severity: 'medium',
    icon: '📦',
    title: 'Seamless.AI Launches Real-Time Data API',
    description: 'Seamless.AI has launched a new developer API offering real-time contact data lookup. Previously a UI-only tool, this marks their first API-first product targeting developers.',
    company_id: 'comp_010',
    company_name: 'Seamless.AI',
    timestamp: '2026-05-22T09:30:00Z',
    source: 'Seamless.AI Blog',
    source_url: 'https://seamless.ai/blog/api-launch',
    ai_analysis: 'Seamless.AI\'s pivot to API-first distribution mirrors the market trend toward developer-oriented data infrastructure. Their entry into the API space increases competitive pressure, though their data quality and coverage lag behind Crustdata. Their $90M revenue provides resources for rapid improvement.'
  },
  {
    id: 'sig_009',
    type: 'funding',
    severity: 'low',
    icon: '💰',
    title: 'Coresignal Raises $12M Series B',
    description: 'Coresignal has raised a $12M Series B to expand its web-sourced B2B data offerings. The company plans to add real-time company event detection and AI-powered data quality scoring.',
    company_id: 'comp_005',
    company_name: 'Coresignal',
    timestamp: '2026-05-20T15:00:00Z',
    source: 'EU-Startups',
    source_url: 'https://eu-startups.com/coresignal-series-b',
    ai_analysis: 'Coresignal\'s funding and product roadmap (real-time events, AI quality scoring) directly overlap with Crustdata\'s capabilities. However, their European base and smaller scale make them a moderate threat. Their strength in web-scraped data could complement or compete depending on go-to-market execution.'
  },
  {
    id: 'sig_010',
    type: 'exec_move',
    severity: 'medium',
    icon: '👔',
    title: 'Former Google DeepMind Researcher Joins Apollo.io as VP of AI',
    description: 'Apollo.io has hired a former Google DeepMind senior researcher as VP of AI. The hire previously led research on large-scale information retrieval and knowledge graph construction.',
    company_id: 'comp_001',
    company_name: 'Apollo.io',
    timestamp: '2026-05-18T12:00:00Z',
    source: 'LinkedIn',
    source_url: 'https://linkedin.com',
    ai_analysis: 'A DeepMind-caliber AI hire at Apollo signals serious investment in AI-native capabilities. Combined with their 15 new AI roles, Apollo is assembling a world-class AI team. Their focus on information retrieval and knowledge graphs aligns directly with the core technical challenges Crustdata solves. This is the most concerning talent signal this quarter.'
  },
  {
    id: 'sig_011',
    type: 'job_posting',
    severity: 'low',
    icon: '💼',
    title: 'Clearbit/HubSpot Posts "Staff Engineer — Data Platform" Role',
    description: 'HubSpot\'s Clearbit division has posted a Staff Engineer role focused on rebuilding the data enrichment pipeline. The posting mentions "real-time data freshness" and "AI agent compatibility" as key requirements.',
    company_id: 'comp_003',
    company_name: 'Clearbit',
    timestamp: '2026-05-16T09:00:00Z',
    source: 'HubSpot Careers',
    source_url: 'https://hubspot.com/careers',
    ai_analysis: 'Clearbit rebuilding its data pipeline with real-time and AI-agent focus confirms the market direction toward Crustdata\'s positioning. HubSpot\'s resources ($2B+ revenue) behind Clearbit make this a long-term strategic threat, though enterprise integration timelines are typically slow.'
  },
  {
    id: 'sig_012',
    type: 'press',
    severity: 'low',
    icon: '📰',
    title: 'Lusha Revenue Drops 12% YoY Per Industry Reports',
    description: 'Industry analysts report Lusha\'s revenue declined approximately 12% year-over-year as the company faces increased competition from AI-native data providers. Headcount has also decreased 8%.',
    company_id: 'comp_008',
    company_name: 'Lusha',
    timestamp: '2026-05-14T11:00:00Z',
    source: 'SaaStr Analysis',
    source_url: 'https://saastr.com/lusha-analysis',
    ai_analysis: 'Lusha\'s declining revenue and headcount validate the market shift from legacy contact databases to API-first, AI-native data platforms. This trend benefits Crustdata directly. Lusha\'s distress may create acquisition opportunities or talent pools to recruit from.'
  },
  {
    id: 'sig_013',
    type: 'product_launch',
    severity: 'critical',
    icon: '🚨',
    title: 'Apollo.io Announces "Apollo Agent SDK" at Developer Conference',
    description: 'Apollo.io has announced the Apollo Agent SDK — a developer toolkit for building AI sales agents with built-in access to Apollo\'s data. The SDK includes MCP server support, structured outputs, and real-time data refresh.',
    company_id: 'comp_001',
    company_name: 'Apollo.io',
    timestamp: '2026-05-12T14:00:00Z',
    source: 'Apollo.io Blog',
    source_url: 'https://apollo.io/blog/agent-sdk',
    ai_analysis: 'This is the most significant competitive product launch of the quarter. Apollo\'s Agent SDK with MCP support directly competes with Crustdata\'s core value proposition as "the data layer for AI agents." Apollo\'s 275M+ contacts database gives them a significant data advantage. However, Crustdata\'s real-time crawling and broader data coverage (company signals, not just contacts) remain key differentiators.'
  },
  {
    id: 'sig_014',
    type: 'talent_flow',
    severity: 'low',
    icon: '🔄',
    title: '5 ZoomInfo Engineers Join Various Startups',
    description: 'Five senior engineers from ZoomInfo\'s data platform team have joined early-stage startups in the past 60 days, including two who joined Y Combinator companies.',
    company_id: 'comp_002',
    company_name: 'ZoomInfo',
    timestamp: '2026-05-10T08:00:00Z',
    source: 'LinkedIn',
    source_url: 'https://linkedin.com',
    ai_analysis: 'ZoomInfo\'s talent exodus to startups represents a recruitment opportunity. These engineers have enterprise-scale data pipeline experience that would be immediately valuable to Crustdata. Recommend targeted outreach to the two who joined YC companies — they understand the ecosystem.'
  },
  {
    id: 'sig_015',
    type: 'hiring_surge',
    severity: 'low',
    icon: '👥',
    title: 'People Data Labs Doubles Sales Team',
    description: 'People Data Labs has doubled its sales team from 8 to 16 in the past quarter, posting roles in SF, NYC, and London. This is the first significant sales investment for the previously developer-only company.',
    company_id: 'comp_004',
    company_name: 'People Data Labs',
    timestamp: '2026-05-08T10:00:00Z',
    source: 'LinkedIn',
    source_url: 'https://linkedin.com/company/peopledatalabs/jobs',
    ai_analysis: 'PDL building a sales team signals a shift from pure PLG to a hybrid sales motion. This move will put them in more enterprise RFPs against Crustdata. Their London expansion also signals international ambitions. The combination of new funding ($66M total), real-time data plans, and a sales team makes PDL the most complete competitive threat in 2026.'
  }
];

export const TALENT_FLOWS = [
  {
    id: 'flow_001',
    from_company: 'Crustdata',
    from_id: 'self_001',
    to_company: 'Apollo.io',
    to_id: 'comp_001',
    count: 3,
    roles: ['Senior Data Engineer', 'ML Engineer', 'Backend Engineer'],
    period: 'Last 3 months',
    direction: 'outflow'
  },
  {
    id: 'flow_002',
    from_company: 'ZoomInfo',
    from_id: 'comp_002',
    to_company: 'Crustdata',
    to_id: 'self_001',
    count: 2,
    roles: ['Staff Engineer', 'Data Scientist'],
    period: 'Last 6 months',
    direction: 'inflow'
  },
  {
    id: 'flow_003',
    from_company: 'ZoomInfo',
    from_id: 'comp_002',
    to_company: 'Apollo.io',
    to_id: 'comp_001',
    count: 8,
    roles: ['Engineering Manager', 'Senior SWE', 'Data Engineer', 'Product Manager'],
    period: 'Last 6 months',
    direction: 'neutral'
  },
  {
    id: 'flow_004',
    from_company: 'Clearbit',
    from_id: 'comp_003',
    to_company: 'Clay',
    to_id: 'comp_006',
    count: 4,
    roles: ['Full-Stack Engineer', 'Product Designer', 'Data Engineer', 'Solutions Architect'],
    period: 'Last 12 months',
    direction: 'neutral'
  },
  {
    id: 'flow_005',
    from_company: 'Google',
    from_id: 'ext_001',
    to_company: 'Crustdata',
    to_id: 'self_001',
    count: 1,
    roles: ['Senior ML Researcher'],
    period: 'Last 3 months',
    direction: 'inflow'
  },
  {
    id: 'flow_006',
    from_company: 'Lusha',
    from_id: 'comp_008',
    to_company: 'People Data Labs',
    to_id: 'comp_004',
    count: 3,
    roles: ['Backend Engineer', 'Data Analyst', 'DevOps Engineer'],
    period: 'Last 6 months',
    direction: 'neutral'
  },
  {
    id: 'flow_007',
    from_company: '6sense',
    from_id: 'comp_009',
    to_company: 'Apollo.io',
    to_id: 'comp_001',
    count: 5,
    roles: ['ML Engineer', 'Product Manager', 'Sales Engineer', 'Data Scientist', 'Frontend Engineer'],
    period: 'Last 12 months',
    direction: 'neutral'
  },
  {
    id: 'flow_008',
    from_company: 'Meta',
    from_id: 'ext_002',
    to_company: 'Crustdata',
    to_id: 'self_001',
    count: 1,
    roles: ['Infrastructure Engineer'],
    period: 'Last 3 months',
    direction: 'inflow'
  }
];

export const INTEL_BRIEFS = [
  {
    id: 'brief_001',
    title: 'Weekly Competitive Intelligence Brief',
    subtitle: 'Week of May 26 — June 1, 2026',
    generated_at: '2026-06-01T08:00:00Z',
    executive_summary: 'The competitive landscape has shifted significantly this week. Apollo.io\'s announcement of the Apollo Agent SDK with MCP support represents the most direct competitive threat to Crustdata\'s core positioning as the data layer for AI agents. Combined with their aggressive AI hiring (15 new roles) and DeepMind VP hire, Apollo is making a well-funded, strategic push into Crustdata\'s territory. Meanwhile, ZoomInfo\'s instability (CTO departure, 15% headcount cuts) creates both talent acquisition opportunities and market share opportunities in the enterprise segment.',
    sections: [
      {
        heading: 'Critical Competitive Moves',
        content: 'Apollo.io has emerged as the primary competitive threat this quarter. Their Agent SDK announcement, combined with 15 new AI/ML hires and a VP of AI from DeepMind, signals a strategic pivot toward AI-native data infrastructure. This is a direct challenge to Crustdata\'s "data layer for AI agents" positioning. Apollo\'s 275M+ contacts database and $251M in funding provide significant resources for execution.'
      },
      {
        heading: 'Market Dynamics',
        content: 'The broader market continues to shift from legacy UI-based tools to API-first, AI-native data platforms. Lusha\'s 12% revenue decline and ZoomInfo\'s headcount reduction validate this trend. Companies that fail to adapt to the AI agent paradigm are losing ground. Crustdata is well-positioned on the right side of this shift, but must accelerate to stay ahead of well-funded competitors now copying the strategy.'
      },
      {
        heading: 'Talent Landscape',
        content: 'Talent flow analysis reveals concerning outflow: 3 Crustdata engineers have moved to Apollo.io in the past 90 days. However, inflow from ZoomInfo (2 engineers) and FAANG companies (Google, Meta) suggests strong employer brand among experienced data engineers. Net talent quality is improving, but the outflow to Apollo requires immediate attention with retention measures.'
      },
      {
        heading: 'Emerging Threats',
        content: 'People Data Labs\' $28M Series C and announced plans for real-time data crawling and MCP server support make them the most complete competitive threat emerging in 2026. Their developer-first positioning, expanding sales team, and international ambitions mirror Crustdata\'s strategy with significantly more capital. Coresignal\'s Series B ($12M) adds another well-funded alternative data competitor to monitor.'
      },
      {
        heading: 'Opportunities',
        content: 'ZoomInfo\'s instability creates a window for enterprise customer acquisition. Clay\'s AI Agent Builder, while potentially commoditizing the data layer long-term, currently serves as a distribution channel that amplifies Crustdata\'s reach. The talent pool from distressed competitors (Lusha, ZoomInfo) offers recruitment opportunities for experienced data infrastructure engineers.'
      }
    ],
    key_risks: [
      'Apollo\'s Agent SDK with MCP support directly competes with Crustdata\'s core value proposition',
      'People Data Labs\' real-time data crawling plans could eliminate Crustdata\'s key differentiator within 6 months',
      'Talent outflow to Apollo (3 engineers) risks transferring institutional knowledge to a direct competitor',
      'HubSpot-backed Clearbit rebuild could leverage $2B+ parent company resources for rapid catch-up'
    ],
    recommended_actions: [
      'Launch competitive response to Apollo Agent SDK — accelerate Crustdata\'s own agent toolkit and developer experience',
      'Implement immediate retention packages for key engineering talent, particularly data pipeline and ML engineers',
      'Initiate targeted recruitment of displaced ZoomInfo data engineers through personalized outreach',
      'Deepen Clay integration to ensure Crustdata is the preferred data provider in Clay\'s AI Agent Builder ecosystem'
    ],
    threat_score: 6.8
  },
  {
    id: 'brief_002',
    title: 'Monthly Strategic Assessment',
    subtitle: 'May 2026',
    generated_at: '2026-05-31T12:00:00Z',
    executive_summary: 'May 2026 marked a turning point in the B2B data intelligence market. The convergence of AI agent frameworks, real-time data infrastructure, and developer-first distribution is reshaping the competitive landscape. Crustdata remains well-positioned as the market pioneer, but the window of competitive advantage is narrowing as well-funded competitors adopt similar strategies.',
    sections: [
      {
        heading: 'Market Evolution',
        content: 'The B2B data market is transitioning from "data as a product" to "data as infrastructure for AI agents." This shift validates Crustdata\'s founding thesis but also attracts new competition. Four competitors (Apollo, PDL, Seamless.AI, Clearbit) have announced API-first or AI-agent capabilities this month alone.'
      },
      {
        heading: 'Competitive Positioning',
        content: 'Crustdata maintains advantages in data freshness (real-time vs. monthly refreshes), breadth of alternative signals (250+ data points), and AI-native architecture. However, Apollo\'s resources and PDL\'s funding are enabling rapid catch-up. The primary moat is shifting from technical capability to data quality and customer lock-in.'
      },
      {
        heading: 'Growth Trajectory',
        content: 'Crustdata\'s 100% headcount growth and estimated $9.2M ARR (up from $6M in January) demonstrate strong momentum. However, maintaining this growth rate requires expansion beyond the YC/developer ecosystem into enterprise accounts — a segment where ZoomInfo\'s instability creates opportunity.'
      }
    ],
    key_risks: [
      'Multiple competitors simultaneously adopting Crustdata\'s key differentiators (real-time data, API-first, AI-native)',
      'Enterprise sales cycle requirements may strain the small team (18 employees)',
      'Data freshness advantage may narrow as competitors invest in crawling infrastructure'
    ],
    recommended_actions: [
      'Invest in proprietary data sources that competitors cannot easily replicate',
      'Build enterprise sales capabilities to capture ZoomInfo churn',
      'Accelerate MCP server ecosystem development to create switching costs'
    ],
    threat_score: 5.9
  }
];

export const MARKET_METRICS = {
  companies_tracked: 11,
  signals_detected: 47,
  signals_this_week: 8,
  threat_score: 6.8,
  briefs_generated: 12,
  talent_moves_tracked: 34,
  data_freshness: '2 min ago'
};
